# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t back .
#       - uses: actions/setup-node@v1
#         with:
#           node-version: '14.5.0'
#       - run: sudo apt-get install xvfb
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: install
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: xvfb-run --auto-servernum mocha test/sohomot-vai.test.js
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: xvfb-run --auto-servernum jest test/mizan-vai.test.js
