# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        uses: actions/setup-node@v1
        with:
          run: npm ci
      - name: xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test
