name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: install packages
        with:
          run: npm ci
      - name: xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:jest
      - name: xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:mocha